#%RAML 0.8
title: PSX sample API
baseUri: http://example.phpsx.org
version: v1
/api/{id}:
  uriParameters:
    id:
      type: integer
  get:
    queryParameters:
      type:
        type: integer
    responses:
      200:
        body:
          application/json:
            schema: !include property.json
  post:
    body:
      application/json:
        schema: !include property.json
    responses:
      200:
        body:
          application/json:
            schema: !include property.json

