#%RAML 0.8
title: World Music API
baseUri: http://example.api.com/{version}
version: v2
traits:
  - paged:
      queryParameters:
        pages:
          description: The number of pages to return
          type: number
/bar/{bar_id}:
  description: Returns details about bar
  uriParameters:
    bar_id:
      type: integer
      description: The id of bar
  get:
    responses:
      200:
        body:
          application/json:
            schema: |
              { "$schema": "http://json-schema.org/draft-04/schema#",
                "type": "object",
                "description": "A canonical song",
                "properties": {
                  "title":  { "type": "string" },
                  "artist": { "type": "string" }
                },
                "required": [ "title", "artist" ]
              }
/foo:
  is: [ paged ]
  description: Some description
  get:
    queryParameters:
      startIndex:
        description: Sets the start index
  post:
    body:
      application/json:
        schema: !include schema.json
    responses:
      200:
        body:
          application/json:
            schema: |
              { "$schema": "http://json-schema.org/draft-04/schema#",
                "type": "object",
                "description": "A canonical song",
                "properties": {
                  "title":  { "type": "string" },
                  "artist": { "type": "string" }
                },
                "required": [ "title", "artist" ]
              }
