#%RAML 0.8
/foo:
  displayName: Test
  description: Test description
  uriParameters:
    fooId:
      type: string
  get:
    description: Test description
    queryParameters:
      foo:
        type: string
        description: Test
      bar:
        type: string
        required: true
      baz:
        type: string
        enum: ["foo", "bar"]
      boz:
        type: string
        pattern: "[A-z]+"
      integer:
        type: integer
      number:
        type: number
      date:
        type: date
      boolean:
        type: boolean
      string:
        type: string
    body:
      application/json:
        schema: !include ../schema/schema.json
    responses:
      200:
        body:
          application/json:
            schema: !include ../schema/schema.json
