#%RAML 0.8
title: World Music API
baseUri: http://example.api.com/{version}
version: v2
traits:
  - fooed: !include params.yaml
  - paged:
      queryParameters:
        pages:
          description: The number of pages to return
          type: number
schemas:
  - body: !include ../schema/schema.json
/bar/{bar_id}:
  description: Returns details about bar
  uriParameters:
    param_integer:
      type: integer
      required: true
      minimum: 8
      maximum: 16
    param_number:
      description: The number
      type: number
    param_date:
      type: date
    param_boolean:
      type: boolean
      required: true
    param_string:
      type: string
      pattern: "[A-z]+"
      minLength: 8
      maxLength: 16
      enum: ["foo", "bar"]
  get:
    responses:
      200:
        body:
          application/json:
            schema: body
/foo:
  displayName: Bar
  description: Some description
  is: [ paged, not_existing, fooed ]
  get:
    description: Informations about the method
  post:
    body:
      application/json:
        schema: !include ../schema/schema.json
    responses:
      200:
        body:
          application/xml:
            schema: |
              <foo />
          application/json:
            schema: |
              { "$schema": "http://json-schema.org/draft-04/schema#",
                "type": "object",
                "description": "A canonical song",
                "properties": {
                  "title":  { "type": "string" },
                  "artist": { "type": "string" }
                },
                "required": [ "title", "artist" ]
              }
      500:
        body:
          application/xml:
            schema: |
              <foo />
  /bar:
    displayName: Bar nested
    description: Some description
    get:
      description: Informations about the method
/invalid_schema:
  post:
    body:
      application/json:
        schema: !include params.yaml
/invalid_reference:
  post:
    body:
      application/json:
        schema: foo
