#%RAML 0.8
version: v4
status: development
/foo:
  displayName: Test v4
  description: Test description v4
  uriParameters:
    fooId4:
      type: string
  get:
    description: Test description v4
    queryParameters:
      string4:
        type: string
    body:
      application/json:
        schema: !include ../schema/schema4.json
    responses:
      200:
        body:
          application/json:
            schema: !include ../schema/schema4.json
