#%RAML 0.8
version: v3
status: active
/foo:
  displayName: Test v3
  description: Test description v3
  uriParameters:
    fooId3:
      type: string
  get:
    description: Test description v3
    queryParameters:
      string3:
        type: string
    body:
      application/json:
        schema: !include ../schema/schema3.json
    responses:
      200:
        body:
          application/json:
            schema: !include ../schema/schema3.json
